# Generated by Django 5.1.1 on 2024-09-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("witnesswords", "0004_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
    ]
