# Generated by Django 5.1.1 on 2024-09-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("witnesswords", "0005_order_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="length",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
