# Generated by Django 5.1.1 on 2024-09-20 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("witnesswords", "0006_order_length"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="length",
            new_name="duration",
        ),
    ]
